blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/anubissbe/alicia-document-assistant/discussions
    about: Please ask and answer questions here
  - name: Security Issue
    url: mailto:bert@telkom.be
    about: Please report security vulnerabilities directly via email